# Numpyの練習

In [1]:
import numpy as np

### 配列について確認する

In [2]:
# numpy配列を生成
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# numpy要素の型を確認　＝　dtype
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [6]:
# 構造を確認　＝　shape
x.shape

(3,)

In [7]:
# 全体の要素数を確認　＝　size
x.size

3

### 配列に要素を追加する

In [18]:
# 追加＝append、挿入＝insert、削除＝delete
# append(元の配列,追加する要素,axis)
# insert(元の配列,挿入する位置=インデックス,追加する要素)
# delete(元の配列,インデックス,axis)

In [11]:
x = np.array([4,5,6])
print(x)
y = np.append(x, [7,8,9])
print(y)

[4 5 6]
[4 5 6 7 8 9]


In [16]:
a = np.insert(y,0,[0,0,0])
print(a)

[0 0 0 4 5 6 7 8 9]


In [20]:
b = np.delete(y,1)
print(b)

[4 6 7 8 9]


In [21]:
b = np.delete(y,[1,2])
print(b)

[4 7 8 9]


### 配列の次元を変換する

In [22]:
x = np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [23]:
# reshape(1次元目の要素数,2次元目の要素数)
# 要素に-1を指定すると、他の次元の要素数から計算して自動設定する
y = x.reshape(2,-1)
print(y)

[[1 2 3]
 [4 5 6]]


### 配列の要素にアクセスする

In [24]:
# [開始:終了:間隔]
x = np.array(range(1,10))
print(x)
print(x[1::2])

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [25]:
# 間隔にマイナスを指定すると最後の要素から順に取り出される
print(x[::-2])

[9 7 5 3 1]


In [26]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1]


In [27]:
# 条件式で抽出することもできる
print(x[x>5])

[6 7 8 9]


### その他便利な命令

In [29]:
# 乱数を生成
# random.rand() = 一様乱数
# random.randn() = 標準正規分布乱数
# random.rand(要素数,次元数)

np.random.rand(10,1)

array([[0.13371167],
       [0.64842383],
       [0.91383784],
       [0.59534782],
       [0.69457713],
       [0.14590978],
       [0.50167584],
       [0.6344323 ],
       [0.16209307],
       [0.37778655]])

In [30]:
# 配列の要素を混ぜる
# shuffle(配列)

x = np.array(range(1,10))
np.random.shuffle(x)
print(x)

[1 8 2 7 4 5 6 3 9]


In [31]:
# 配列を並び替える
# sort(配列)

y = np.sort(x)
print(y)

[1 2 3 4 5 6 7 8 9]


In [32]:
# 配列同士を結合する
# vstack((配列１,配列２,...))

a = np.array([1,2,3])
b = np.array([4,5,6])
z = np.vstack((a,b))
print(z)

[[1 2 3]
 [4 5 6]]


In [36]:
np.random.rand(3,2)

array([[0.30404788, 0.57156806],
       [0.38165188, 0.77614183],
       [0.5208459 , 0.53356244]])

In [37]:
np.random.rand(3,2,1)

array([[[0.28187803],
        [0.32634695]],

       [[0.88596385],
        [0.2179657 ]],

       [[0.74251487],
        [0.85014225]]])